// Package types — Build #46.x Webhook data model.
//
// A Webhook is a tenant-owned outbound subscription: "when event X
// fires, POST the payload to URL Y". Each subscription signs its
// outbound requests with an HMAC-SHA256 of the body using the row's
// Secret, so receivers can verify the source without trusting TLS
// alone.
package types

import (
	"database/sql/driver"
	"encoding/json"
	"errors"
	"time"
)

// WebhookEvent names one of the closed set of events that can flow
// through the outbound webhook bus.
type WebhookEvent string

const (
	WebhookEventCollabDocCreated  WebhookEvent = "collab.doc.created"
	WebhookEventCollabDocUpdated  WebhookEvent = "collab.doc.updated"
	WebhookEventCollabDocArchived WebhookEvent = "collab.doc.archived"
	WebhookEventCollabDocDeleted  WebhookEvent = "collab.doc.deleted"
	WebhookEventCollabDocShared   WebhookEvent = "collab.doc.shared"
	WebhookEventCollabDocUploaded WebhookEvent = "collab.doc.uploaded"
	WebhookEventCollabDocExported WebhookEvent = "collab.doc.exported"

	WebhookEventCollabCommentAdded    WebhookEvent = "collab.comment.added"
	WebhookEventCollabCommentResolved WebhookEvent = "collab.comment.resolved"

	WebhookEventSlideDeckCreated       WebhookEvent = "slide.deck.created"
	WebhookEventSlideDeckUpdated       WebhookEvent = "slide.deck.updated"
	WebhookEventSlideDeckAutoGenerated WebhookEvent = "slide.deck.auto_generated"
)

// ValidWebhookEvents is the closed allow-list enforced at the API edge.
var ValidWebhookEvents = map[WebhookEvent]bool{
	WebhookEventCollabDocCreated:  true,
	WebhookEventCollabDocUpdated:  true,
	WebhookEventCollabDocArchived: true,
	WebhookEventCollabDocDeleted:  true,
	WebhookEventCollabDocShared:   true,
	WebhookEventCollabDocUploaded: true,
	WebhookEventCollabDocExported: true,
	WebhookEventCollabCommentAdded:    true,
	WebhookEventCollabCommentResolved: true,
	WebhookEventSlideDeckCreated:       true,
	WebhookEventSlideDeckUpdated:       true,
	WebhookEventSlideDeckAutoGenerated: true,
}

// WebhookEventList is the storage representation of the subscription
// event allow-list. The column is JSONB (mysql TEXT) so we implement
// sql.Scanner / driver.Valuer round-tripping here.
type WebhookEventList []WebhookEvent

// Value marshals the list to JSON for storage.
func (l WebhookEventList) Value() (driver.Value, error) {
	if l == nil {
		return "[]", nil
	}
	return json.Marshal([]WebhookEvent(l))
}

// Scan parses JSON bytes from storage back into the list.
func (l *WebhookEventList) Scan(src interface{}) error {
	if src == nil {
		*l = nil
		return nil
	}
	var b []byte
	switch v := src.(type) {
	case []byte:
		b = v
	case string:
		b = []byte(v)
	default:
		return errors.New("webhook events: unsupported scan source")
	}
	if len(b) == 0 {
		*l = nil
		return nil
	}
	var out []WebhookEvent
	if err := json.Unmarshal(b, &out); err != nil {
		return err
	}
	*l = out
	return nil
}

// MarshalJSON serialises the list as a JSON array.
func (l WebhookEventList) MarshalJSON() ([]byte, error) {
	if l == nil {
		return []byte("[]"), nil
	}
	return json.Marshal([]WebhookEvent(l))
}

// UnmarshalJSON parses a JSON array into the list.
func (l *WebhookEventList) UnmarshalJSON(b []byte) error {
	var out []WebhookEvent
	if err := json.Unmarshal(b, &out); err != nil {
		return err
	}
	*l = out
	return nil
}

// Contains reports whether the given event is in the list.
func (l WebhookEventList) Contains(e WebhookEvent) bool {
	for _, x := range l {
		if x == e {
			return true
		}
	}
	return false
}

// Webhook is the row representation.
type Webhook struct {
	ID             string          `json:"id"             gorm:"primaryKey;type:varchar(36)"`
	TenantID       uint64          `json:"tenant_id"      gorm:"index"`
	Name           string          `json:"name"           gorm:"type:varchar(128)"`
	URL            string          `json:"url"            gorm:"type:varchar(512)"`
	Events         WebhookEventList `json:"events"        gorm:"type:text"`
	Secret         string          `json:"-"              gorm:"type:varchar(128)"`
	Active         bool            `json:"active"         gorm:"default:true"`
	LastDeliveryAt *time.Time      `json:"last_delivery_at,omitempty" gorm:""`
	LastError      string          `json:"last_error,omitempty"      gorm:"type:varchar(1024);default:''"`
	CreatedBy      uint64          `json:"created_by"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

func (Webhook) TableName() string { return "webhooks" }

type WebhookDelivery struct {
	ID           string       `json:"id"             gorm:"primaryKey;type:varchar(36)"`
	WebhookID    string       `json:"webhook_id"     gorm:"index;type:varchar(36)"`
	TenantID     uint64       `json:"tenant_id"      gorm:"index"`
	Event        WebhookEvent `json:"event"          gorm:"type:varchar(64)"`
	Payload      JSON         `json:"payload"        gorm:"type:text"`
	Status       string       `json:"status"         gorm:"type:varchar(16);default:'pending'"`
	Attempts     int          `json:"attempts"       gorm:"default:0"`
	NextRetryAt  *time.Time   `json:"next_retry_at,omitempty" gorm:""`
	ResponseCode int          `json:"response_code"  gorm:"default:0"`
	ResponseBody string       `json:"response_body,omitempty" gorm:"type:varchar(2048);default:''"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeliveredAt  *time.Time   `json:"delivered_at,omitempty" gorm:""`
}

func (WebhookDelivery) TableName() string { return "webhook_deliveries" }

const (
	WebhookDeliveryStatusPending = "pending"
	WebhookDeliveryStatusSuccess = "success"
	WebhookDeliveryStatusFailed  = "failed"
)

type CreateWebhookRequest struct {
	Name   string         `json:"name"`
	URL    string         `json:"url"`
	Events []WebhookEvent `json:"events"`
	Secret string         `json:"secret,omitempty"`
	Active *bool          `json:"active,omitempty"`
}

func (r *CreateWebhookRequest) Validate() error {
	if r.URL == "" {
		return errors.New("webhook: url is required")
	}
	if len(r.Events) == 0 {
		return errors.New("webhook: at least one event is required")
	}
	for _, e := range r.Events {
		if !ValidWebhookEvents[e] {
			return errors.New("webhook: unknown event " + string(e))
		}
	}
	if r.Secret != "" && len(r.Secret) < 16 {
		return errors.New("webhook: secret must be at least 16 chars when provided")
	}
	return nil
}

type UpdateWebhookRequest struct {
	Name   *string         `json:"name,omitempty"`
	URL    *string         `json:"url,omitempty"`
	Events *[]WebhookEvent `json:"events,omitempty"`
	Active *bool           `json:"active,omitempty"`
	Secret *string         `json:"secret,omitempty"`
}

type ListWebhooksFilter struct {
	ActiveOnly bool
	Limit      int
	AfterID    string
}
