package types

import (
	"errors"
)

// WikiTemplateAutoChildSourceRef is the source_refs tag stamped onto
// pages that were generated by the template skeleton engine. The
// service uses it to find and delete prior auto-generated children
// during a rebuild (Q2=A — atomic delete-then-create).
//
// We deliberately re-use WikiPage.SourceRefs rather than adding a new
// column: SourceRefs is already indexed in wiki_pages, and a JSON
// array of short tokens is the canonical way the system tags how a
// page came into existence (see WikiPage.SourceRefs doc comment).
const WikiTemplateAutoChildSourceRef = "auto-template"

// WikiTemplateAutoChildSourceRefMaxLen caps the optional sub-token
// appended to "auto-template" (e.g. "auto-template:meeting"). Long
// suffixes would bloat the column without improving recall.
const WikiTemplateAutoChildSourceRefMaxLen = 64

// WikiTemplatePlaceholderChild is one row of the skeleton.children[]
// block. The frontend parses the markdown body for these placeholders:
//
//	{{child_pages}}        → catalog of all auto-generated children
//	{{child_section}}      → in-page anchor list of all sections
//	{{tagged_pages:foo}}   → list of pages tagged `foo` in this KB
//
// At apply time the user picks a template (or supplies raw children),
// the backend creates the children in one transaction, and replaces
// the placeholders inside the parent body with the resolved HTML/MD.
type WikiTemplatePlaceholderChild struct {
	// Slug is optional — when omitted the service derives
	// "<parent_slug>-<slugify(title)>". Slugs must be unique within the
	// KB; the service appends a numeric suffix on collision.
	Slug string `json:"slug,omitempty"`
	// Title is the visible page title. Required.
	Title string `json:"title" binding:"required"`
	// Content is the seed body. When empty the new page is created
	// with an empty body — the user fills it in later.
	Content string `json:"content,omitempty"`
	// DefaultTags are pre-applied via the Build #17 tag system.
	// Stored on the child page's WikiPageTag associations.
	DefaultTags []string `json:"default_tags,omitempty"`
}

// WikiTemplatePlaceholderSection is one row of skeleton.sections[].
// Applied at the {{child_section}} placeholder as an in-page anchor
// with a markdown heading + the section's body. Used to materialise
// per-child stub headings inside the parent body without forcing the
// user to write them by hand.
type WikiTemplatePlaceholderSection struct {
	// Anchor is the markdown anchor id (no `#`). The service
	// reuses it verbatim if non-empty; otherwise it slugifies Title.
	Anchor string `json:"anchor,omitempty"`
	// Title is the heading text (level 2 by default).
	Title string `json:"title" binding:"required"`
	// Body is the markdown body rendered under the heading.
	Body string `json:"body,omitempty"`
}

// WikiTemplateSkeleton is the JSON sub-tree of WikiPageTemplate that
// the apply-template engine consumes. Kept as a dedicated type so the
// frontend / backend wire format stays in lock-step.
//
// Validation:
//   - len(Children) + len(Sections) + len(TaggedTokens) <= 200 (safety)
//   - per-Slug uniqueness (handled by service during rewrite)
//   - per-Anchor uniqueness across Sections (handled by service)
type WikiTemplateSkeleton struct {
	Children     []WikiTemplatePlaceholderChild   `json:"children,omitempty"`
	Sections     []WikiTemplatePlaceholderSection `json:"sections,omitempty"`
	TaggedTokens []string                         `json:"tagged_tokens,omitempty"`
}

// WikiApplyTemplateRequest is the body for POST /pages/:slug/apply-template.
//
// SourceRef is appended to each new child's SourceRefs after the
// canonical "auto-template" tag. Lets the operator trace the
// template origin in audit logs and source-ref chips.
type WikiApplyTemplateRequest struct {
	// TemplateID stamps source_refs with the originating template.
	// Optional — useful when applying a saved template by id.
	TemplateID string `json:"template_id,omitempty"`
	// BodyOverride replaces the parent's body verbatim. Optional —
	// when omitted the service reads the current body, parses
	// placeholders, and rewrites only the placeholder tokens.
	// Mutually exclusive with BodyAppend.
	BodyOverride string `json:"body_override,omitempty"`
	// BodyAppend, when non-empty, is appended to the existing parent
	// body after placeholders are resolved. Used by the "重建子页面"
	// button to keep the user's tail content intact.
	BodyAppend string `json:"body_append,omitempty"`
	// Skeleton describes the children + sections to materialise.
	// Required.
	Skeleton WikiTemplateSkeleton `json:"skeleton" binding:"required"`
}

// WikiApplyTemplateResult is what the handler returns after a
// successful apply. Pages is the auto-generated child set; Sections
// lists the in-page anchors that were inserted into the parent body;
// TaggedPages counts how many wiki_pages matched each tagged token.
type WikiApplyTemplateResult struct {
	ParentSlug  string                            `json:"parent_slug"`
	ParentTitle string                            `json:"parent_title"`
	Pages       []WikiApplyTemplateCreatedPage    `json:"pages"`
	Sections    []WikiApplyTemplateResolvedSection `json:"sections"`
	TaggedPages map[string][]string                `json:"tagged_pages"`
	// NewBody is the rewritten parent body — empty when the request
	// did not produce any placeholder rewrites.
	NewBody string `json:"new_body,omitempty"`
}

// WikiApplyTemplateCreatedPage describes one auto-generated child.
type WikiApplyTemplateCreatedPage struct {
	Slug  string `json:"slug"`
	Title string `json:"title"`
}

// WikiApplyTemplateResolvedSection describes one in-page section
// anchor that was inserted.
type WikiApplyTemplateResolvedSection struct {
	Anchor string `json:"anchor"`
	Title  string `json:"title"`
}

// Sentinel errors specific to template skeleton apply.
var (
	// ErrWikiTemplateEmptySkeleton fires when the caller submits a
	// skeleton with zero children + zero sections + zero tagged
	// tokens. We refuse to spin up a no-op apply — the front end
	// should pick at least one or omit the request entirely.
	ErrWikiTemplateEmptySkeleton = errors.New("wiki template skeleton is empty")

	// ErrWikiTemplateOversizeSkeleton fires when the combined
	// children + sections + tagged tokens exceed the safety cap.
	// 200 matches the rough maximum a human will reasonably maintain.
	ErrWikiTemplateOversizeSkeleton = errors.New("wiki template skeleton exceeds 200 entries")
)

// WikiTemplateSkeletonSafetyCap is the public upper bound used by
// the request validator. Service references the same constant.
const WikiTemplateSkeletonSafetyCap = 200